name: Quality assurance

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: 'PHPStan PHP ${{ matrix.php }} + ${{ matrix.variant }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.1'
            variant: 'symfony/symfony:"2.8.*"'
            config: symfony_2.neon
          - php: '7.1'
            variant: 'symfony/symfony:"3.0.*"'
            config: symfony_3.neon
          - php: '7.1'
            variant: 'symfony/symfony:"3.1.*"'
            config: symfony_3.neon
          - php: '7.1'
            variant: 'symfony/symfony:"3.2.*"'
            config: symfony_3.neon
          - php: '7.1'
            variant: 'symfony/symfony:"3.3.*"'
            config: symfony_3.neon
          - php: '7.1'
            variant: 'symfony/symfony:"3.4.*"'
            config: symfony_3.neon
          - php: '7.1'
            variant: 'symfony/symfony:"4.0.*"'
            config: symfony_4.1.neon
          - php: '7.1'
            variant: 'symfony/symfony:"4.1.*"'
            config: symfony_4.1.neon
          - php: '7.1'
            variant: 'symfony/symfony:"4.2.*"'
            config: symfony_4.neon
          - php: '7.1'
            variant: 'symfony/symfony:"4.3.*"'
            config: symfony_4.neon
          - php: '7.1'
            variant: 'symfony/symfony:"4.4.*"'
            config: symfony_4.neon
          - php: '7.2'
            variant: 'symfony/symfony:"5.0.*"'
            config: symfony_5.neon
          - php: '7.2'
            variant: 'symfony/symfony:"5.1.*"'
            config: symfony_5.neon
          - php: '7.2'
            variant: 'symfony/symfony:"5.2.*"'
            config: symfony_5.neon
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install variant
        if: matrix.variant != 'normal'
        run: composer require ${{ matrix.variant }} --no-update

      - name: Install PHPStan
        run: |
          composer require phpstan/phpstan:"0.12.*" --no-update
          composer require phpstan/phpstan-phpunit:"0.12.*" --no-update

      - name: Install variant
        if: matrix.variant != 'normal'
        run: composer require ${{ matrix.variant }} --no-update

      - name: 'Install Composer dependencies (${{ matrix.dependencies }})'
        uses: 'ramsey/composer-install@v1'
        with:
          dependency-versions: '${{ matrix.dependencies }}'
          composer-options: '--prefer-dist --prefer-stable'

      - name: Run PHPStan
        run: vendor/bin/phpstan --memory-limit=1G analyse -c ${{ matrix.config }}

  php-cs-fixer:
    name: PHP CS Fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: none
          tools: composer:v2, cs2pr, php-cs-fixer

      - name: Install Composer dependencies (highest)
        uses: 'ramsey/composer-install@v1'
        with:
          dependency-versions: 'highest'
          composer-options: '--prefer-dist --prefer-stable'

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --format checkstyle | cs2pr
