name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: 'PHP ${{ matrix.php }} + ${{ matrix.dependencies }} + ${{ matrix.variant }}'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - lowest
          - highest
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        experimental: [false]
        variant: [normal]
        phpstan: [.phpstan/symfony_5.neon]
        include:
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"2.8.*"'
            phpstan: .phpstan/symfony_2.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"3.0.*"'
            phpstan: .phpstan/symfony_3.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"3.1.*"'
            phpstan: .phpstan/symfony_3.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"3.2.*"'
            phpstan: .phpstan/symfony_3.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"3.3.*"'
            phpstan: .phpstan/symfony_3.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"3.4.*"'
            phpstan: .phpstan/symfony_3.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"4.0.*"'
            phpstan: .phpstan/symfony_4.1.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"4.1.*"'
            phpstan: .phpstan/symfony_4.1.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"4.2.*"'
            phpstan: .phpstan/symfony_4.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"4.3.*"'
            phpstan: .phpstan/symfony_4.neon
          - php: '7.1'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"4.4.*"'
            phpstan: .phpstan/symfony_4.neon
          - php: '7.2'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"5.0.*"'
            phpstan: .phpstan/symfony_5.neon
          - php: '7.2'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"5.1.*"'
            phpstan: .phpstan/symfony_5.neon
          - php: '7.2'
            dependencies: highest
            experimental: false
            variant: 'symfony/symfony:"5.2.*"'
            phpstan: .phpstan/symfony_5.neon
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure coverage driver
        id: coverage
        run: echo ::set-output name=driver::$([ "${{ matrix.php }}" = "7.1" ] && echo "xdebug" || echo "pcov")

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ steps.coverage.outputs.driver }}
          tools: composer:v2

      - name: Install variant
        if: matrix.variant != 'normal'
        run: composer require ${{ matrix.variant }} --no-update

      - name: 'Install Composer dependencies (${{ matrix.dependencies }})'
        uses: 'ramsey/composer-install@v1'
        with:
          dependency-versions: '${{ matrix.dependencies }}'

      - name: Run Tests
        run: vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

      - name: Send coverage results to Scrutinizer CI
        if: matrix.php != '8.0'
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover build/coverage-clover.xml

      - name: Send coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: 'PHP ${{ matrix.php }} + ${{ matrix.dependencies }} + ${{ matrix.variant }}'
        if: matrix.php != '8.0'
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls -x build/coverage-clover.xml -o build/coveralls-upload.json -v

      - name: Install PHPStan
        run: |
          composer global require phpstan/phpstan:"0.12.*"
          composer global require phpstan/phpstan-phpunit:"0.12.*"

      - name: Run PHPStan
        run: phpstan --memory-limit=1G analyse -c ${{ matrix.phpstan }}
